### ISSUE TITLE
value are URI encode twice

### ISSUE THREAD

**Issue by renoke** [jillix/url.js#14]
When one call updateSearchParam() function the value is encode twice. First in the function (Line 119) then when stringify() function is called at line 126. The stringify function encode itself the query object. For exemple "foo bar" is encoded as "foo%25%20bar" instead of "foo%20bar" (% is encoded as %25...)... which may cause bug if params are reused afterwards.

**Comment by IonicaBizau** [comment]
Thanks for the report, @renoke! Indeed it's a :bug:. I'm investigating and probably will push a fix soon. :mag:

**Comment by renoke** [comment]
One solution might to update updateSearchParam function like this 
```javascript
    function updateSearchParam(param, value) {
        var searchParsed = parseQuery();

        // Delete the parameter
        if (value === undefined) {
            delete searchParsed[param];
        } else {
            // Update or add
            var valueEncoded = encodeURIComponent(value);
            if (searchParsed[param] === valueEncoded) {
                return Url;
            }
            searchParsed[param] = value;
        }

        var newSearch = "?" + stringify(searchParsed);
        window.history.replaceState(null, "", newSearch + location.hash);

        return Url;
    }

**Comment by IonicaBizau** [comment]
@renoke Actually the `encodeURIComponent` is not needed. I think I introduced it just to hide some problem in the `parseQuery`, but now the `parseQuery` returns the correct result and `encodeURICompoenent` is not needed anymore.

Btw, the [demo page](http://jillix.github.io/url.js/) already runs the `1.2.0` version. Could you please check it out? :sparkle:
