### ISSUE TITLE
Can't distinguish between a lack of value and an empty value

### ISSUE THREAD

**Issue by lolmaus** [jillix/url.js#17]
Given these urls:

* `http://example.com`
* `http://example.com?foo`
* `http://example.com?foo=`

evaluating `Url.queryString("foo")` gives identical result: `""`.

I expect this behavior instead:

* `http://example.com` -- `false` or `null` or `undefined`
* `http://example.com?foo` -- `true`
* `http://example.com?foo=` -- `""`

This is a major bug to me. Consider this current behavior:

```js
// Given URL http://example.com
const foo = Url.queryString("foo");
Url.updateSearchParam("foo", foo);
// Now the URL is different from what it was initially, even though we set the same value as we got.
```

**Comment by IonicaBizau** [comment]
> I expect this behavior instead:

I agree. :+1: Currently, I work on other things, but feel free to hack it and send us a pull request. I will take care of it.

It should be done in [this function](https://github.com/jillix/url.js/blob/819615da5a715d328ff406cbf58a184cd53e4caf/src/url.js#L23), probably. :thought_balloon:

**Comment by lolmaus** [comment]
No time to hack into it either, I'm sorry. :(

> It should be done in this function, probably. :thought_balloon:

I believe all four main methods require the update. E. g. `updateSearchParam('foo', true)` currently results in `?foo=true`, should be `?foo`.

**Comment by IonicaBizau** [comment]
I'm on it. Wish me success. :smile:
