### ISSUE TITLE
Support for hash params

### ISSUE THREAD

**Issue by lolmaus** [jillix/url.js#18]
Would be nice to manipulate hash params without having to download another library.

**Comment by IonicaBizau** [comment]
> Would be nice to manipulate hash params without having to download another library.

Well, isn't that just `location.hash = "some-hash"` and `var someHash = location.hash.substring(1)`?

**Comment by lolmaus** [comment]
Why do you need this lib in the first place? `location.search = someString` works just like you suggest for `location.hash`. :trollface:

**Comment by IonicaBizau** [comment]
> location.search = someString works just like you suggest for location.hash

`location.search = someString` reloads the whole page while `location.hash` doesn't.
But if you need specific helper functions like `Url.hash = function () { return location.hash.substring(1); }` and so on, feel free to specify that.

**Comment by lolmaus** [comment]
What I mean is an ability to manipulate individual hash entries as opposed to overwriting the whole hash. I. e. `updateSearchParam` and `queryString` counterparts.

**Comment by IonicaBizau** [comment]
@lolmaus Is there a specific use case? Maybe an example would be useful. :thought_balloon:

**Comment by IonicaBizau** [comment]
@lolmaus In `2.0.0` I added the `hash` method which sets/gets the hash (without the `#` character). :ship: **`2.0.0`** :tada:

**Comment by lolmaus** [comment]
Setting the whole hash can be achieved via `window.location.hash`, it makes little sense to replicate it in a library.

The idea is to be able to get/set hash key/value pairs individually.

**Comment by IonicaBizau** [comment]
@lolmaus Well, like I mentioned before, we accept contributions. Just feel free to raise a good pull request and we will take care of it. :sparkle:
