### ISSUE TITLE
Source

### ISSUE THREAD

**Issue by joshuabaker** [jillix/url.js#21]
Super helpful library. Thanks for sharing. :+1: 

Might you be able to share the uncompressed source for this?

**Comment by IonicaBizau** [comment]
@joshuabaker Glad to hear it's helpful! :four_leaf_clover: 

Check out the [`lib/index.js`](https://github.com/jillix/url.js/blob/master/lib/index.js) file. There you can see the human-readable, uncompressed source. The `src` dir contains the minified version. :sparkle:
