### ISSUE TITLE
is Not supported  ie 9 < ?

### ISSUE THREAD

**Issue by dangyuqiang** [jillix/url.js#28]
i9  prompt
对象不支持"replaceState"属性或方法

**Comment by IonicaBizau** [comment]
Does IE9 still exist? 😁  

`replaceState` is not compatible with IE<11: http://caniuse.com/#feat=history

**Comment by dangyuqiang** [comment]
There is no way compatible with IE9,IE8 ? i want to   .thanks !.Or I modify the code?

**Comment by IonicaBizau** [comment]
Use a polyfill like this; https://github.com/devote/HTML5-History-API
I have no idea if it is working or not. 💥

**Comment by dangyuqiang** [comment]
HTML5-History-API Stability and good compatibility?

**Comment by IonicaBizau** [comment]
Try it—have no idea. :grin:

**Comment by dangyuqiang** [comment]
thank you very much！

**Comment by vxsx** [comment]
for the record, ie11 doesn't support es6 shorthand properties (among other things), so unless you're transpiling on your own, it's not really usable there either
