### ISSUE TITLE
First property of object returned by parseQuery() contains base URL when a string is passed

### ISSUE THREAD

**Issue by philipstratford** [jillix/url.js#36]
If you call `parseQuery()` with a string parameter, the returned object's first property contains the base URL in the property's key. For example:
````
let testUrl = "https://notarealurl.com?foo=1&bar=2";
let urlParams = Url.parseQuery(testUrl);
alert(JSON.stringify(urlParams));
````
returns
````
{ "https://notarealurl.com?foo": "1", "bar": "2" }
````

I've made a fiddle [here](https://jsfiddle.net/philipstratford/o9apbj56/)

**Comment by IonicaBizau** [comment]
Well, that works as expected because parseQuery really parses an input which is supposed to contain only the query (location.search by default).
