### ISSUE TITLE
v0.3.1 commit has no associated tag or release

### ISSUE THREAD

**Issue by silviubogan** [jillix/url.js#6]
I talk about this commit: bf68b428c166092a6ad9a7de70bd5818e762b85d.

**Comment by IonicaBizau** [comment]
https://github.com/jillix/url.js/releases/tag/v0.3.1

:+1:

**Comment by IonicaBizau** [comment]
Probably because I released it after a IE :hankey: debugging session.

**Comment by gabipetrovay** [comment]
":hankey:" :laughing:

**Comment by IonicaBizau** [comment]
It's a :hankey: and it looks nice and happy.

...and it doesn't smell! :smiley:

**Comment by gabipetrovay** [comment]
It's a happy :hankey:!

**Comment by IonicaBizau** [comment]
Actually, is not that bad: https://twitter.com/peter_miller/status/575361363469430784 :smile:
